WIP: Add telemetry to track metrics
quantum-elixir/quantum-core pull request #453
Opened 2020-09-01 00:00 UTC by mrmarcsmith

See #415 

I have added the sending of "add", "update", and "delete" events via telemetry. I have also injected assertions into the existing job_broardcast_tests file to verify functionality of the telemetry events.

Up next I plan to add "job execution (including return value / error / execution time)"

2020-09-02 23:34 UTC, mrmarcsmith commented
@maennchen when you get back from vacation I would love your feedback on this!

2020-09-03 17:55 UTC, rraub commented
@mrmarcsmith It would probably be worth adding some documentation around how a user would consume these telemetry events in the readme or the other markdown doc folder.

2020-09-03 17:57 UTC, mrmarcsmith commented
@rraub good idea! I’ll work on that

2020-09-07 09:20 UTC, maennchen requested changes
@mrmarcsmith Thanks a lot for the PR!

There's a few cases I think we should handle:

* `JobBroadcaster` / `init` should call `[ :quantum, :job, :add ]` for all jobs
* `JobBroadcaster` / `delete_all` should call `[ :quantum, :job, :delete ]` for all jobs
* `[:quantum, :job, *]` should contain the job itself in the metadata
* `[:quantum, :job, *]` should contain the scheduler module name itself in the metadata (if someone has multiple schedulers)

2020-09-09 00:00 UTC, mrmarcsmith commented
@maennchen I have completed your requested changes. I am wondering if passing `module: __MODULE__` in the metadata was what you were asking for in point 4 because that was already present

2020-09-09 09:19 UTC, maennchen commented
@mrmarcsmith This is not exactly what I meant with the module:

There's a name for the main scheduler. This would for example be `Acme.Scheduler` (The module that contains the `use Quantum` code)

`JobBroadcaster`: This module name is available as `scheduler` in the [`State`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/job_broadcaster.ex#L72).

`Executor`: The `scheduler` is not yet passed to the executor module. It has to be passed from the [`Supervisor`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/supervisor.ex#L102) to [`ExecutorSupervisor.start_link/1`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/executor_supervisor.ex#L16) to [`ExecutorSupervisor.init/1`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/executor_supervisor.ex#L47) to [`Executor.execute/3`](https://github.com/quantum-elixir/quantum-core/blob/master/lib/quantum/executor.ex#L27).

2020-09-09 09:20 UTC, maennchen commented
@mrmarcsmith PS: Sorry for the merge conflict. Can you solve it our should I resolve it before merge?

2020-09-09 18:20 UTC, mrmarcsmith commented
@maennchen Sounds good! I can take of those merge conflicts

2020-09-10 23:59 UTC, mrmarcsmith commented
@maennchen This is ready to be re-reviewed. I ended up adding the scheduler option to the following opts modules so i could pass the scheduler around. Can you think of any end user rational for accessing these ops modules directly that might be a breaking change? 
- Quantum.ExecutorSupervisor.StartOpts
- Quantum.ExecutorSupervisor.InitOpts
- Quantum.Executor.StartOpts

2020-09-11 07:42 UTC, maennchen requested changes
We also need to trigger an update event here:

* https://github.com/quantum-elixir/quantum-core/pull/453/files#diff-2d3fae9a29455d58e947c99642c86ecbR134
* https://github.com/quantum-elixir/quantum-core/pull/453/files#diff-2d3fae9a29455d58e947c99642c86ecbR196

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor.ex
> +  @spec run(Node.t(), Job.t(), GenServer.server(), boolean(), Scheduler) :: Task.t()
```suggestion
  @spec run(Node.t(), Job.t(), GenServer.server(), boolean(), Module.t()) :: Task.t()
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor/start_opts.ex
> +          scheduler: Scheduler
```suggestion
          scheduler: Module.t()
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor_supervisor/init_opts.ex
> +          scheduler: Scheduler
```suggestion
          scheduler: Module.t()
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor_supervisor/start_opts.ex
> +          scheduler: Scheduler
```suggestion
          scheduler: Module.t()
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor.ex
> +        module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor.ex
> +            module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/executor.ex
> +            module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +              module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +          module: __MODULE__,
```suggestion
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +        :telemetry.execute([:quantum, :job, :delete], %{}, %{
This will only be executed for active jobs. I think we also want to call it on inactive ones.

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +        :telemetry.execute([:quantum, :job, :add], %{}, %{
We‘re overriding an existing job here:

```suggestion
        :telemetry.execute([:quantum, :job, :update], %{}, %{
```

2020-09-11 07:42 UTC, maennchen commented on lib/quantum/job_broadcaster.ex
> +        :telemetry.execute([:quantum, :job, :add], %{}, %{
We‘re overriding an existing job here:

```suggestion
        :telemetry.execute([:quantum, :job, :update], %{}, %{
```

2020-09-11 07:43 UTC, maennchen commented
@mrmarcsmith This is for sure not a vreaking change. The modules are not documented and therefore considered internal.

2020-09-11 21:11 UTC, mrmarcsmith commented
@maennchen dialyzer is throwing `Unknown type: Module.t/0` on the change you made. How do you want to proceed?

2020-09-11 21:14 UTC, maennchen commented
@mrmarcsmith Oops, that's not the first time i make this error. Should just be atom().

2020-09-11 21:15 UTC, mrmarcsmith commented
testing now

2020-09-11 21:16 UTC, maennchen commented
@mrmarcsmith After this change it's ready to merge 😊

2020-09-11 21:17 UTC, mrmarcsmith commented
local test and dialyzer passed! Thank you for the help

2020-09-11 21:25 UTC, maennchen approved these changes

2020-09-11 21:28 UTC, merged